inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec_rails
  - rubocop-factory_bot

AllCops:
  SuggestExtensions: true
  NewCops: enable

RSpecRails/InferredSpecType:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
