# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "CI"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Set up database schema
        run: bin/rails db:create db:migrate
      - name: Run tests
        run: bundle exec rspec
      - name: Run active record doctor
        run: bundle exec rake active_record_doctor
  lint:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Run bundle-audit
        run: bundle exec bundle-audit
      - name: Run rails_best_practices
        run: bundle exec rails_best_practices
      - name: Run brakeman
        run: bundle exec brakeman
