# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "CI"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.1-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: linhsa_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      CONSOLE_USER: user
      CONSOLE_PASSWORD: password
      DATABASE_URL: "postgres://rails:password@localhost:5432/linhsa_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: prebuilt
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: build assets
        run: bin/rails assets:precompile
      - name: Set up database schema
        run: bin/rails db:create db:migrate
      - name: Run tests
        run: bundle exec rspec
      - name: Coveralls
        uses: coverallsapp/github-action@v2
      - name: Run active record doctor
        run: bundle exec rake active_record_doctor
  lint:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: prebuilt
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Run rails_best_practices
        run: bundle exec rails_best_practices
      - name: Run erb html lint
        run: bundle exec erblint --lint-all
      - name: Run brakeman
        run: bundle exec brakeman

  eslint:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: prebuilt
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install packages
        run: yarn
      - name: Run eslint
        run: yarn lint
